### ISSUE TITLE
Node 8 compatibility

### ISSUE THREAD

**Issue by bjornharrtell** [isleofcode/ember-cordova-installer#1]
I find `^4.5 || 6.* || 7.*` in `package.json` disallowing use under Node 8. Limited tests seems to indicate it works though.

**Comment by jamesdixon** [comment]
@alexblom I see something was fixed with this in the main ember-cordova repo, but I still get this error when running `yarn install`:

```
[2/4] 🚚  Fetching packages...
error ember-cordova-installer@0.0.1: The engine "node" is incompatible with this module. Expected version "^4.5 || 6.* || 7.*".
error Found incompatible module
```

**Comment by alexblom** [comment]
Thanks for the follow up
